package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// exampleConfig is a minimal working monika-go configuration.
const exampleConfig = `# Example monika-go configuration generated by 'createConfig'.
# See https://monika.hyperjump.tech/guides/probes for the full reference.
probes:
  - id: github
    name: GitHub test
    description: Probe github.com and alert when it does not return 200
    requests:
      - url: https://github.com
        method: GET
        timeout: 7000
        alerts:
          - assertion: response.status == 200
            message: GitHub did not return 200

  - id: httpbin
    name: httpbin
    description: Probe every 30 seconds, skip response bodies
    interval: 30
    requests:
      - url: https://httpbin.org/status/200
        method: GET
        timeout: 7000
        saveBody: false

notifications:
  - id: desktop-01
    type: desktop
`

var createConfigOut string

// createConfigCmd writes an example configuration file to get started quickly.
var createConfigCmd = &cobra.Command{
	Use:   "createConfig",
	Short: "Write an example monika configuration file",
	Long:  `Writes a minimal working monika-go configuration file to the path given by --out (default monika.yaml). Refuses to overwrite an existing file.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if _, err := os.Stat(createConfigOut); err == nil {
			return fmt.Errorf("%s already exists, refusing to overwrite", createConfigOut)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat %s: %w", createConfigOut, err)
		}
		if err := os.WriteFile(createConfigOut, []byte(exampleConfig), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", createConfigOut, err)
		}
		fmt.Println("example config written to", createConfigOut)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(createConfigCmd)
	createConfigCmd.Flags().StringVar(&createConfigOut, "out", "monika.yaml", "path of the example config file to write")
}
