name: Github Actions - Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: none
  actions: write
  pull-requests: read    

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.24
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Load test dependencies
      run: |        
        go install honnef.co/go/tools/cmd/staticcheck@latest  
        go install golang.org/x/vuln/cmd/govulncheck@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Static checking
      run: |
        go mod verify
        staticcheck -checks all ./...
    
    - name: Security vulnerabilities scan
      run: govulncheck -show verbose ./...

    - name: Security check
      run: gosec ./...

    - name: Test project
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Build image
      run: go build -a -ldflags '-extldflags "-static"' -o monika-go main.go

    - name: Build docker
      run: docker build . --file ./Dockerfile -t monika-go:$(date +%s)
